// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv-rFRBZZU_TM_Xgz3MoWW6BlUx6gRkr4',
    appId: '1:653587836148:web:2cc983d893d3c04be982a1',
    messagingSenderId: '653587836148',
    projectId: 'expense-tracker-9ff4f',
    authDomain: 'expense-tracker-9ff4f.firebaseapp.com',
    storageBucket: 'expense-tracker-9ff4f.firebasestorage.app',
    measurementId: 'G-QMPJ8LMK1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS4qkMS-ze_BdgXzQv4Lm-wpKF97Ingfg',
    appId: '1:653587836148:android:c903d2243cc819a5e982a1',
    messagingSenderId: '653587836148',
    projectId: 'expense-tracker-9ff4f',
    storageBucket: 'expense-tracker-9ff4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs3SZWDSxB02NAv8amHhwo82XKBh9rLlM',
    appId: '1:653587836148:ios:d205514359fd865fe982a1',
    messagingSenderId: '653587836148',
    projectId: 'expense-tracker-9ff4f',
    storageBucket: 'expense-tracker-9ff4f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs3SZWDSxB02NAv8amHhwo82XKBh9rLlM',
    appId: '1:653587836148:ios:d205514359fd865fe982a1',
    messagingSenderId: '653587836148',
    projectId: 'expense-tracker-9ff4f',
    storageBucket: 'expense-tracker-9ff4f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv-rFRBZZU_TM_Xgz3MoWW6BlUx6gRkr4',
    appId: '1:653587836148:web:88db5803f03011dfe982a1',
    messagingSenderId: '653587836148',
    projectId: 'expense-tracker-9ff4f',
    authDomain: 'expense-tracker-9ff4f.firebaseapp.com',
    storageBucket: 'expense-tracker-9ff4f.firebasestorage.app',
    measurementId: 'G-WX48X3R1JE',
  );
}
